import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {io} from 'socket.io-client'
import { useState } from 'react'

export default function Home() {
  const socket = io('https://sheltered-coast-56651.herokuapp.com/')
  const [message, setMessage] = useState('Not connected')

  socket.on('connect', () => {
    console.log(`connected with id: ${socket.id}`)
  })
  
  const sendInfo = () => {
    alert('sending')
    socket.emit('greeting', 'Hello world!')
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>{message}</p>
        <button onClick={sendInfo}>Hello</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
